### ISSUE TITLE
Option to select a transformed image size missing

### ISSUE THREAD

**Issue by paul-frost** [pixelandtonic/RedactorI#1]
I feel bad pointing it out, as it's great that this is available, and It's really the text processing I wanted back. But if you are going to insert images into text it would be much better to be able to choose from the transforms as well.

**Comment by brandonkelly** [comment]
That is already possible. Make sure you're running the latest version of Craft 2.5 though (2.5.2752 or later), as we fixed a bug where the "Select transform" button was not showing up for Rich Text fields, and the bug would affect Redactor I as well.
