### ISSUE TITLE
toolbarFixedBox not pinning toolbar to top?

### ISSUE THREAD

**Issue by RitterKnightCreative** [pixelandtonic/RedactorI#2]
As you scroll down, the toolbar should stay pinned to the top of the screen.

Duped a working config from an old Craft 2.4 install to test it (which hasn't been updated to 2.5 yet):

    {
	buttons: ['html', 'formatting', 'bold', 'italic', 'deleted', 'unorderedlist', 'orderedlist', 'outdent', 'indent', 'image', 'file', 'link', 'alignment', 'horizontalrule','video'],
	plugins: ['fullscreen','table','video'],
	toolbarFixedBox: true
    }

Otherwise seems to be working well. (Not a big fan of Redactor II's text toolbar.)

**Comment by RitterKnightCreative** [comment]
Noticed the offending CSS is coming from Craft 2.5 in [craft.css](https://github.com/pixelandtonic/Craft-Release/blob/master/app/resources/css/craft.css#L1519). It's using ``!important`` which is overriding the style in the plugin. Craft 2.4 didn't have this...

**Comment by brandonkelly** [comment]
Should work using `toolbarFixed: true`

**Comment by brandonkelly** [comment]
We just fixed this in [Craft 2.6.2798](https://craftcms.com/changelog#build2798). Note that the setting is `toolbarFixed`, not `toolbarFixedBox`.
