### ISSUE TITLE
Redactor I plugin with Craft 2.6

### ISSUE THREAD

**Issue by khamer** [pixelandtonic/RedactorI#3]
I believe that the Redactor I plugin **does not work** with Craft 2.6. After upgrading to Craft 2.6, everything appears fine, but if I go into edit any field (even one that isn't a Redactor I field) I get the following with Line 38 highlighted:

```
Variable "assetSourceOptions" does not exist


/var/www/.../dev/craft/app/templates/_components/fieldtypes/RichText/settings.html(38)

26 
27 {{ forms.field({
28     label: "Config"|t,
29     instructions: "You can save custom Redactor configs as .json files in craft/config/redactor/."|t~' <a href="http://imperavi.com/redactor/docs/settings/" target="_blank">'~"View available settings"|t~'</a>.',
30     id: 'configFile'
31 }, configInput) }}
32 
33 {{ forms.checkboxSelectField({
34     id: 'availableAssetSources',
35     name: 'availableAssetSources',
36     label: 'Available Image Sources'|t,
37     instructions: 'The asset sources that should be available when selecting images (if the selected config has an Image button).'|t,
38     options: assetSourceOptions,
39     values: settings.availableAssetSources,
40 }) }}
41 
42 {{ forms.checkboxSelectField({
43     id: 'availableTransforms',
44     name: 'availableTransforms',
45     label: 'Available Image Transforms'|t,
46     instructions: 'The image transforms that should be available when selecting images (if the selected config has an Image button).'|t,
47     options: transformOptions,
48     values: settings.availableTransforms,
49 }) }}
50 
```

Once I disable the plugin, it immediately works again. I tried replacing the entirety of craft/app with a copy from a fresh ZIP of Craft, but it didn't make any difference.

**Comment by benjamminf** [comment]
Just wanted to say I'm getting the same error and also think it's an incompatibility issue with 2.6

**Comment by benjamminf** [comment]
Did a bit of digging into the code and found since 2.6 the Rich Text field type (Redactor II) has additional field attributes for selecting asset and asset transform sources. I've put together a fix for this issue by copying an pre-2.6 settings template file of the Rich Text field type into the plugin and using that instead. I'll open a pull request very soon.

**Comment by benjamminf** [comment]
Haha okay so seems like @brandonkelly beat me to it by a few hours. Cheers for that mate!

**Comment by takobell** [comment]
Pull the latest on the master branch and that error will be fixed.  Not an official release yet since there are some other things needed for 2.6 compatibility, but that'll get rid of the main error.
