### ISSUE TITLE
Center aligning broken

### ISSUE THREAD

**Issue by zachshallbetter** [pixelandtonic/RedactorI#4]
The editor removes text center aligned text when "Clean up HTML" is enabled on the field. All other alignment works appropriately.

**Comment by JuanjoSalvador** [comment]
By unchecking "Clean up HTML" in field config, we can fix this, but... Is reliable this workaround? I mean, can it break something?

**Comment by brandonkelly** [comment]
Sorry for missing this. Closing because the plugin isn’t officially supported anymore.

We don’t recommend unchecking “Clean up HTML”, though. I’d recommend you uninstall Redactor I and attempt with Craft’s built-in Redactor II editor.
