### ISSUE TITLE
Inline style buttons do not appear anymore in Redactor I - Craft 2.6

### ISSUE THREAD

**Issue by migswd** [pixelandtonic/RedactorI#5]
Hello Craft team.
I got problem after Craft update from 2.4 to 2.6
I am happy to see that you did a redactor plugin I but it does not work for me.

So here what I had in 2.4 
Bunch of cool inline buttons in redactor for my client ( "q","sup","sub","small","nobr" ) thanks to great **inlinestyles** plugin by Carlcs (https://github.com/carlcs/craft-redactorinlinestyles/)
![screen shot 2016-07-24 at 22 40 55](https://cloud.githubusercontent.com/assets/3531623/17086423/01054e16-51f2-11e6-8882-c2edc98ea688.jpg)
And this config
![screen shot 2016-07-24 at 22 44 30](https://cloud.githubusercontent.com/assets/3531623/17086424/13a6c914-51f2-11e6-9914-5893798944b0.jpg)

But now in Craft 2.6 the buttons do not appear anymore
![screen shot 2016-07-24 at 22 58 54](https://cloud.githubusercontent.com/assets/3531623/17086437/4e29db9e-51f2-11e6-8722-2c868b31b9ef.jpg)

Any idea what is the problem ?

**Comment by brandonkelly** [comment]
Sorry for missing this. Going to close it because it’s been so long, and this plugin isn’t officially supported anymore.
