### ISSUE TITLE
Unordered lists bullets missing

### ISSUE THREAD

**Issue by hubertprein** [pixelandtonic/RedactorI#8]
Copied from the release 2.6.2964 (https://craftcms.com/changelog#2-6-2964)

* Fixed a bug where unordered lists in Rich Text fields weren’t getting bullets.

This doesn't work in RedactorI as well. Could we have a fix please?

**Comment by mijar** [comment]
The bugfix would be highly appreciated! It is very painful for our users to work with it now and we have to fix a lot of content they want to include but mess with it because of the bug...
Thanks in advance!

**Comment by brandonkelly** [comment]
Fixed for [version 1.1.1](https://github.com/pixelandtonic/RedactorI/releases/tag/1.1.1).
