### ISSUE TITLE
Bold, Italic, Underline no longer working in Chrome

### ISSUE THREAD

**Issue by jbutts-nerdery** [pixelandtonic/RedactorI#9]
Shortly after upgrading Craft to 2.6.2980, I noticed the bold, italic, underline, and strikethrough buttons no longer work in Chrome 58.0.3029.110. They do work in FF and Safari on Mac.

**Comment by alexbech** [comment]
I'm having the same issues with Craft 2.6.2978

**Comment by brandonkelly** [comment]
Able to reproduce, but this is a browser compatibility issue with Redactor, not something caused by a Craft update. (I’m also seeing it on Craft 2.6.2976.)

I’d recommend you just uninstall the plugin and use Craft’s built-in Redactor II editor. Its stability has improved dramatically.
